DROP TABLE IF EXISTS tickets;
DROP TABLE IF EXISTS books;
DROP TABLE IF EXISTS readers;

CREATE TABLE IF NOT EXISTS readers (
    id INT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(100) NOT NULL,
    surname VARCHAR(100) NOT NULL,
    login VARCHAR(100) NOT NULL,
    password VARCHAR(100) NOT NULL,
    enable BOOLEAN NOT NULL,
    authority VARCHAR(100) NOT NULL,
    UNIQUE (name, surname)
);

CREATE TABLE IF NOT EXISTS books (
    id INT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(100) NOT NULL,
    author VARCHAR(100) NOT NULL,
    year VARCHAR(4) NOT NULL,
    amount INT NOT NULL,
    UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS tickets (
    id INT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    reader_id INT NOT NULL REFERENCES readers (id) ON DELETE CASCADE,
    book_id INT NOT NULL REFERENCES books (id) ON DELETE CASCADE,
    date_from VARCHAR(16) NOT NULL,
    date_to VARCHAR(16),
    UNIQUE (reader_id, book_id)
);

INSERT INTO readers (name, surname, login, password, enable, authority) VALUES
('Bruce', 'Willis', 'diehard', '123', 'true', 'ROLE_READER'),
('Michel', 'Jackson', 'king', '777', 'true', 'ROLE_READER'),
('Jeff', 'Bezos', 'rocketman', '2021', 'true', 'ROLE_ADMIN');

INSERT INTO books (name, author, year, amount) VALUES
('Cloud Atlas', 'David Mitchell', '2004', '1'),
('Erich Maria Remarque', 'Triumphal Arch', '1945', '6'),
('Jack London', 'Martin Eden', '1909', '2'),
('Stephen King', 'On Writing: A Memoir of the Craft', '2010', '4'),
('Joseph John Campbell', 'The Hero with a Thousand Faces', '1949', '5');

INSERT INTO tickets (reader_id, book_id, date_from, date_to) VALUES
(1, 4, '2020-04-18 13:12', '2020-05-12 17:00'),
(1, 2, '2021-03-24 17:05', '2021-04-01 14:35'),
(2, 1, '2021-03-27 11:00', '2021-04-14 12:48'),
(2, 2, '2021-05-01 09:55', '2021-05-07 18:06'),
(3, 3, '2021-07-11 14:13', '2021-07-19 13:01');