CREATE TABLE IF NOT EXISTS books (
    id INT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    name VARCHAR(40) NOT NULL,
    author VARCHAR(40) NOT NULL,
    year VARCHAR(4) NOT NULL,
    UNIQUE (name)
)