CREATE TABLE IF NOT EXISTS books (
    id INT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    name VARCHAR(100) NOT NULL,
    author VARCHAR(100) NOT NULL,
    year VARCHAR(4) NOT NULL,
    busy BOOLEAN NOT NULL,
    UNIQUE (name)
)